version: '3.4'
services:
  mssql-server:
    container_name: myapp-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "password@12345#"
      MSSQL_PID: Developer
    ports:
      - "8002:1433"
  codefirst-app:
    build: .
    environment:
        DatabaseServer: "mssql-server"
        DatabasePort: "1433"
        DatabasePassword: "password@12345#"
        DatabaseName: "codefirst"
    ports:
    - "8090:80"
 