version: '3.4'
networks:
  mynetwork:
    external: true 
services:
  mssql-server:
    container_name: myapp-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "minhtai123@"
      MSSQL_PID: Developer
    ports:
      - "8002:1433"
    networks: 
      - mynetwork
  codefirst-app:
    build: .
    environment:
        DatabaseServer: "mssql-server"
        DatabasePort: "1433"
        DatabasePassword: "minhtai123@"
        DatabaseName: "codefirst"
    ports:
    - "8090:80"
    networks: 
    - mynetwork
 